 export const STATIC_VARIABLES = [
    // Basis
    "typeFlat",
    "isGrondgebonden",
    "isPortiekflat", 
    "isGalerieflat",
    "breed",
    "diepte",
    "goothoogte",
    "zadeldak",
    "aantalWoningen",
    "hoogte",
  
    // Deuren
    "voordeur_breedte",
    "voordeur_hoogte",
    "achterdeur_breedte",
    "achterdeur_hoogte",
  
    // Woonkamer
    "woonkamer_raam1_breedte",
    "woonkamer_raam1_hoogte",
    "woonkamer_raam2_breedte",
    "woonkamer_raam2_hoogte",
    "woonkamer_raam3_breedte",
    "woonkamer_raam3_hoogte",
    "woonkamer_breedte",
    "woonkamer_lengte",
  
    // Woonkamer 2
    "woonkamer2_raam1_breedte",
    "woonkamer2_raam1_hoogte",
    "woonkamer2_raam2_breedte",
    "woonkamer2_raam2_hoogte",
    "woonkamer2_raam3_breedte",
    "woonkamer2_raam3_hoogte",
  
    // Slaapkamer 1
    "slaapkamer1_raam1_breedte",
    "slaapkamer1_raam1_hoogte",
    "slaapkamer1_raam2_breedte",
    "slaapkamer1_raam2_hoogte",
    "slaapkamer1_breedte",
    "slaapkamer1_lengte",
  
    // Slaapkamer 1 (2)
    "slaapkamer1_2_raam1_breedte",
    "slaapkamer1_2_raam1_hoogte",
  
    // Slaapkamer 2
    "slaapkamer2_raam1_breedte",
    "slaapkamer2_raam1_hoogte",
    "slaapkamer2_raam2_breedte",
    "slaapkamer2_raam2_hoogte",
    "slaapkamer2_breedte",
    "slaapkamer2_lengte",
  
    // Overige kamers
    "achterkamer_breedte",
    "achterkamer_lengte",
    "slaapkamer3_breedte",
    "slaapkamer3_lengte",
    "keuken_breedte",
    "keuken_lengte",
    "badkamer_breedte",
    "badkamer_lengte",
    "hal_breedte",
    "hal_lengte",
    "toilet_breedte",
    "toilet_lengte"
  ] as const;
