import "../scss/main.scss";
import { Inter } from "next/font/google";
import { DataProvider } from "@/contexts/DataContext";
import { Metadata } from "next";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create ",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <DataProvider>
          <main>{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
