import "../scss/main.scss";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import PasswordProtection from "@/modules/PasswordProtection";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Verduurzamings versneller",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/pwq8zgw.css" />
      </head>
      <PasswordProtection>
        <body className={`${inter.variable} antialiased`}>
          <main>{children}</main>
        </body>
      </PasswordProtection>
    </html>
  );
}
